### ISSUE TITLE
Tell me about your work! 

### ISSUE THREAD

**Issue by brianamarie** [githubschool/graph-ql#1]

**Comment by githubteacher** [comment]
My most recent PRs are: <br> 1. [fix url in readme](https://github.com/githubteacher/github-games/pull/1)<br> 1. [Add participant file for @githubteacher](https://github.com/githubteacher/intro-to-github-june-2017/pull/5)<br> 1. [Update README to include Mastering Markdown guide](https://github.com/githubteacher/intro-to-github-june-2017/pull/12)<br> 1. [What is this day good for?](https://github.com/githubteacher/my-site/pull/2)<br> 1. [Copyright on README](https://github.com/githubteacher/my-site/pull/3)<br>

**Comment by githubteacher** [comment]
My most recent PRs are: <br> 1. [fix url in readme](https://github.com/githubteacher/github-games/pull/1)<br> 1. [Add participant file for @githubteacher](https://github.com/githubteacher/intro-to-github-june-2017/pull/5)<br> 1. [Update README to include Mastering Markdown guide](https://github.com/githubteacher/intro-to-github-june-2017/pull/12)<br> 1. [What is this day good for?](https://github.com/githubteacher/my-site/pull/2)<br> 1. [Copyright on README](https://github.com/githubteacher/my-site/pull/3)<br>
