### ISSUE TITLE
Test Issue - Help Me Obi Wan!

### ISSUE THREAD

**Issue by JustinMarchi** [githubschool/graph-ql#105]
💯

**Comment by JustinMarchi** [comment]
@githubteacher  do I need access to edit my comment through the GraphQL API Explorer?

**Comment by JustinMarchi** [comment]
@githubteacher @githubrobot I keep getting this when I try to execute the query:

{
  "data": {
    "addComment": null
  },
  "errors": [
    {
      "message": "Although you appear to have the correct authorization credentials,\nthe `githubschool` organization has enabled OAuth App access restrictions, meaning that data\naccess to third-parties is limited. For more information on these restrictions, including\nhow to whitelist this app, visit\nhttps://help.github.com/articles/restricting-access-to-your-organization-s-data/\n",
      "type": "FORBIDDEN",
      "path": [
        "addComment"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}

**Comment by raini35** [comment]
@JustinMarchi I also got this error and I was wondering if you managed to solve it?
