### ISSUE TITLE
Here are my recent contributions

### ISSUE THREAD

**Issue by githubstudent** [githubschool/graph-ql#3]

**Comment by githubstudent** [comment]
My most recent contributions are to: <br> 1. [b-a-n-a-n-a-s](https://github.com/hectorsector/b-a-n-a-n-a-s)<br> 1. [local-teacherbot](https://github.com/githubschool/local-teacherbot)<br> 1. [animated-invention](https://github.com/githubschool/animated-invention)<br> 1. [graph-ql](https://github.com/githubschool/graph-ql)<br> 1. [atlanta](https://github.com/github-scholars/atlanta)<br>

**Comment by filipows** [comment]
yada yada yada

**Comment by filipows** [comment]
yada yada yada

**Comment by filipows** [comment]
yada yada yada
