### ISSUE TITLE
In Xanadu...

### ISSUE THREAD

**Issue by CPlommer** [githubschool/graph-ql#39]
...did Kubla Kahn a stately pleasure dome decree.
testing mutations in GraphQL

**Comment by CPlommer** [comment]
My most recent contributions are to: <br>
1. [repository1](url1)<br>
1. [repository2](url2)<br>
1. [repository3](url3)<br>
1. [repository4](url4)<br>
1. [repository5](url5)<br>

**Comment by CPlommer** [comment]
[contribution template]

**Comment by CPlommer** [comment]
My most recent contributions are to: <br>1. [repository1](url1)<br>1. [repository2](url2)<br>1. [repository3](url3)<br>1. [repository4](url4)<br>1. [repository5](url5)<br>

**Comment by CPlommer** [comment]
:)

**Comment by arcecio** [comment]
My most recent contributions are to: <br>1. [ProjectAlphaJavaAPI](https://github.com/arcecio/ProjectAlphaJavaAPI)<br>1. [ProjectAlphaAdminWebApp](https://github.com/arcecio/ProjectAlphaAdminWebApp)<br>

**Comment by CPlommer** [comment]
#THUMB_UP

**Comment by CPlommer** [comment]
THUMBS_UP

**Comment by CPlommer** [comment]
fsadf

**Comment by CPlommer** [comment]
THUMBS_UP

**Comment by CPlommer** [comment]
fgadsfsda

**Comment by CPlommer** [comment]
<b>fgadsfsda<b>

**Comment by CPlommer** [comment]
+1

**Comment by CPlommer** [comment]
/reactions/heart

**Comment by CPlommer** [comment]
:EMOJICODE:

**Comment by CPlommer** [comment]
:+1:

**Comment by CPlommer** [comment]
:+1:<br>https://help.github.com/articles/basic-writing-and-formatting-syntax/#using-emoji
