### ISSUE TITLE
Recent repos

### ISSUE THREAD

**Issue by cro** [githubschool/graph-ql#4]

**Comment by cro** [comment]
My most recent contributions are to: <br> 1. [salt](https://github.com/saltstack/salt)<br> 1. [trueos-core](https://github.com/trueos/trueos-core)<br> 1. [karabiner](https://github.com/tekezo/Karabiner-Elements)<br> 1. [barnacle](https://github.com/cachedout/barnacle)<br> 1. [hoverupdate](https://github.com/cro/hoverupdate)<br>

**Comment by lopjavier93** [comment]
[contribution template]

**Comment by lopjavier93** [comment]
My most recent contributions are to: <br> 1. [repository1](ttps://github.com/githubschool/on-demand-github-pages)<br>
