### ISSUE TITLE
learn teach code

### ISSUE THREAD

**Issue by rouzbeh84** [githubschool/graph-ql#53]
hack night

**Comment by rouzbeh84** [comment]
My most recent contributions are to: <br> 1. [repository1](url1)<br> 1. [repository2](url2)<br> 1. [repository3](url3)<br> 1. [repository4](url4)<br> 1. [repository5](url5)<br>

**Comment by rouzbeh84** [comment]
My most recent contributions are to: <br> 1. [office-simulator](https://github.com/tholman/office-simulator)

**Comment by rouzbeh84** [comment]
My most recent contributions are to: <br> 2. [learn-teach-code](https://github.com/learnteachcode)

**Comment by redfit** [comment]
hello world

**Comment by redfit** [comment]
hello world

**Comment by redfit** [comment]
hello world

**Comment by redfit** [comment]
hello world

**Comment by redfit** [comment]
hello world

**Comment by redfit** [comment]
hello world

**Comment by redfit** [comment]
hello world

**Comment by redfit** [comment]
hello world

**Comment by rouzbeh84** [comment]
Stop please
