### ISSUE TITLE
Flamboyant Flamingos Running Rampant

### ISSUE THREAD

**Issue by jwmcneelyiii** [githubschool/graph-ql#75]
Something must be done.

**Comment by jwmcneelyiii** [comment]
My most recent contributions are to: <br>
 1. [oauth-ng](https://github.com/angularjs-oauth/oauth-ng)<br>
 1. [installer_portal](https://github.com/jwmapana/installer_portal)<br>

**Comment by jwmapana** [comment]
&#1F600;

**Comment by jwmapana** [comment]
HOORAY

**Comment by crichID** [comment]
Best issue title ever! :sparkles: @jwmapana

**Comment by jwmcneelyiii** [comment]
Thanks!
