### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by akkimah** [githubschool/graph-ql#76]
Describe what you need help with here.
@githubteacher 
please help me i am getting trouble in code of finding issue id in Graph-ql
query FindIssueID {
  repository(owner: "githubschool", name: "graph-QL") {
    issue(number: #11016){
    id
    }
  }
}
solution ide
{
  "data": null,
  "errors": [
    {
      "message": "Parse error on \"}\" (RCURLY) at [10, 5]",
      "locations": [
        {
          "line": 10,
          "column": 5
        }
      ]
    }
  ]
}

**Comment by crichID** [comment]
> issue(number: #11016){

@akkimah the problem is that your issue number is invalid for this repository. You will need to replace it with your issue number (#76)
