### ISSUE TITLE
API related issue

### ISSUE THREAD

**Issue by abhishek2f24** [githubschool/graph-ql#80]
How to make an API specific related to a topic into whole webpage?

**Comment by crichID** [comment]
@ABHISHEK2F24 I believe you are asking how to embed API data into a web-page. This is a great question and there are many, many ways to accomplish it. Here are a few links from a Google search  that can get you started:

- https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data
- https://blog.hellojs.org/fetching-api-data-with-react-js-460fe8bbf8f2
- https://scotch.io/tutorials/how-to-use-the-javascript-fetch-api-to-get-data
