### ISSUE TITLE
My recent work

### ISSUE THREAD

**Issue by talktopri** [githubschool/graph-ql#9]
👀

**Comment by talktopri** [comment]
My most recent contributions are to: <br> 1. [sep-27-developers](https://github.com/githubteacher/sep-27-developers)<br> 1. [assignment_html_resume](https://github.com/vikingeducation/assignment_html_resume)<br> 1. [assignment_viking_css_garden](https://github.com/vikingeducation/assignment_viking_css_garden)<br> 1. [speaking_git](https://github.com/talktopri/speaking_git)<br> 1. [A-Place-For-My-Head](https://github.com/talktopri/A-Place-For-My-Head)<br>

**Comment by capripot** [comment]
My most recent contribution (maybe): [awesomo](https://github.com/lk-geimfari/awesomo)
